### ISSUE TITLE
为什么echats的gallery打不开，官方实例就可以打开，求解

### ISSUE THREAD

**Issue by vikky-lynn** [ecomfe/echarts-gallery-feedback#1]
![image](https://cloud.githubusercontent.com/assets/26075813/23387701/3798bd98-fd99-11e6-82e2-22b16371265a.png)
![image](https://cloud.githubusercontent.com/assets/26075813/23387708/46fa0ad0-fd99-11e6-95f2-8ad54946f3f9.png)

**Comment by pissang** [comment]
控制台报错了没？

**Comment by vikky-lynn** [comment]
@pissang 两个错误
![image](https://cloud.githubusercontent.com/assets/26075813/23389014/610eec04-fda0-11e6-93c6-4403dd4bfc10.png)
麻烦帮我看下是什么原因，谢谢

**Comment by vikky-lynn** [comment]
@pissang 换了几个浏览器都不行

**Comment by bessieqing** [comment]
我的也不行，最近打不开，缓存清了，浏览器也换了几个试了

**Comment by ethanyaol** [comment]
我也是，最近经常出现这样的问题
