### ISSUE TITLE
投票：你是否愿意付费VIP比如50一年，来使用MakeAPie这样的图表服务？

### ISSUE THREAD

**Issue by suqi** [ecomfe/echarts-gallery-feedback#100]
愿意请扣1， 如果人多我考虑复制出一个新的MakeAPie，不过需要收费50一年，来维持网站开支。

**Comment by suqi** [comment]
@xugaofan

**Comment by x814566371** [comment]
1

**Comment by kangaroo1122** [comment]
1

**Comment by quqingfei** [comment]
1

**Comment by suqi** [comment]
抱歉各位，我发起投票后一个月，只有6个人投票支持，这样的话，基本上我是无法收回成本的，所以我还是放弃这个计划，谢谢各位！

**Comment by quqingfei** [comment]
你直接在网站上放个额充值二维码。我愿意充值！你直接提问，很多人进入网站，找不到你这个git地址。。。根本没法投票。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Matt ***@***.***&gt;; 
发送时间: 2022年2月23日(星期三) 晚上10:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ecomfe/echarts-gallery-feedback] 投票：你是否愿意付费VIP比如50一年，来使用MakeAPie这样的图表服务？ (Issue #100)





 
抱歉各位，我发起投票后一个月，只有6个人投票支持，这样的话，基本上我是无法收回成本的，所以我还是放弃这个计划，谢谢各位！
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
