### ISSUE TITLE
查看部分分支示例，通过官网点击进去后，界面不显示，错误描述如下图

### ISSUE THREAD

**Issue by LegendBlackCat** [ecomfe/echarts-gallery-feedback#11]
[https://pan.baidu.com/s/1gg1bIy3](url)

**Comment by Ovilia** [comment]
示例的地址是？

**Comment by LegendBlackCat** [comment]
有好几个，我记不清了，大概是有这个[http://gallery.echartsjs.com/editor.html?c=xHyRFHJYDe](url)

**Comment by Ovilia** [comment]
刷新看看？我这边可以访问这个地址。
换一下浏览器试试？

**Comment by LegendBlackCat** [comment]
刷新自然就可以了，我也换过别的暂时没毛病，可能是浏览器的问题，我只是随便测了一下QQ浏览器而已。

**Comment by Ovilia** [comment]
可能是有些资源没加载上吧，刷新 ok 就行~
