### ISSUE TITLE
echarts 官网怎么了  打开一堆错。

### ISSUE THREAD

**Issue by liu983074833** [ecomfe/echarts-gallery-feedback#17]
![image](https://user-images.githubusercontent.com/29528207/42309434-24d02808-806b-11e8-9768-6e2486b73e93.png)

**Comment by IcemBerry** [comment]
我也发现有同样的问题，且社区分享的图表都无法打开，确认不是网络问题
![error](https://user-images.githubusercontent.com/28218278/42309763-24103448-806c-11e8-9f96-a32ef11a72aa.png)

**Comment by Ovilia** [comment]
服务器有时候不稳定，抱歉带来困扰。如果还有问题，请根据新的 issue 模板给我们提供 debug 信息，谢谢！
