### ISSUE TITLE
echart官网经常出问题

### ISSUE THREAD

**Issue by lazybird23** [ecomfe/echarts-gallery-feedback#18]

**Comment by wingmeng** [comment]
me too，访问 Echarts gallery 跳转到百度贴吧404是什么鬼？
![image](https://user-images.githubusercontent.com/9009389/43297627-0a0f6b8e-9185-11e8-8c76-88bc7e61b71b.png)

![image](https://user-images.githubusercontent.com/9009389/43297641-1dccf024-9185-11e8-8404-6dddc1714d0a.png)

**Comment by ReliaMM** [comment]
同上经常性的出现这样的错误，而且编辑提交到社区也经常出现问题

**Comment by Ovilia** [comment]
服务器有时候不稳定，抱歉带来困扰。如果还有问题，请根据新的 issue 模板给我们提供 debug 信息，谢谢！
