### ISSUE TITLE
官网能修复下么？有查看不了了

### ISSUE THREAD

**Issue by dongchuanwen** [ecomfe/echarts-gallery-feedback#27]
Failed to load resource: the server responded with a status of 405 (Method Not Allowed)
explore.html:1 Failed to load http://static.tieba.baidu.com/tb/error.html?tc=22300913610473613066082114: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://gallery.echartsjs.com' is therefore not allowed access.
2static.tieba.baidu.com/tb/error.html?tc=22404684750473613066082114:1 Failed to load resource: the server responded with a status of 405 (Method Not Allowed)
explore.html#sort=rank~timeframe=all~author=all:1 Failed to load http://static.tieba.baidu.com/tb/error.html?tc=22404684750473613066082114: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://gallery.echartsjs.com' is therefore not allowed access.

**Comment by Ovilia** [comment]
服务器有时候不稳定，抱歉带来困扰。如果还有问题，请根据新的 issue 模板给我们提供 debug 信息，谢谢！
