### ISSUE TITLE
关于Gallery权限设置

### ISSUE THREAD

**Issue by wuruihua** [ecomfe/echarts-gallery-feedback#3]
创建的示例demo 保存时的权限设置部分的---输入密码可读--没有效果

**Comment by Ovilia** [comment]
谢谢反馈，正在修复

**Comment by wuruihua** [comment]
建议增加权限---仅可以浏览图表效果 不可查看代码---（保护作者版权）

**Comment by wuruihua** [comment]
建议增加权限---仅可以浏览图表效果 不可查看代码---（保护作者版权）

**Comment by Ovilia** [comment]
@wuruihua 不可查看代码的功能是不合适的，我们希望通过这样的开源平台，让更多人学习分享。不可查看代码是不符合这一开源精神的。

**Comment by Ovilia** [comment]
密码分享的 bug 已修复，感谢反馈！
