### ISSUE TITLE
gallery 页面中加载不出来图

### ISSUE THREAD

**Issue by yiyuqi** [ecomfe/echarts-gallery-feedback#33]
## 问题描述

……

### 如果是 Gallery 打不开

请在下面提供 tracecode 以便我们排查问题。

Tracecode:

Chrome：页面右键【检查】，在 Network 面板内，刷新后选择 html（如 `explore.html`），在右边的 Headers 中找到“Tracecode”填在上方。

没有提供该信息的 issue 将自动关闭。

**Comment by mcjiji** [comment]
Request URL:http://static.tieba.baidu.com/tb/error.html?tc=24928927570823640586082316
Request Method:OPTIONS
Status Code:405 Method Not Allowed

**Comment by Ovilia** [comment]
未按 issue 模板提供 tracecode
