### ISSUE TITLE
Gallery 打不开

### ISSUE THREAD

**Issue by YuThree** [ecomfe/echarts-gallery-feedback#34]
## 问题描述

……

### 如果是 Gallery 打不开

请在下面提供 tracecode 以便我们排查问题。

Tracecode:

Chrome：页面右键【检查】，在 Network 面板内，刷新后选择 html（如 `explore.html`），在右边的 Headers 中找到“Tracecode”填在上方。

没有提供该信息的 issue 将自动关闭。

**Comment by YuThree** [comment]
Gallery 打不开 Tracecode：04382643280823640586082716

**Comment by dolonfly** [comment]
我的也打不开 Tracecode ：24154150990823640586082716

**Comment by ruiger** [comment]
Tracecode | 27815319360823640586082716
网站是不是挂了，都打不开了

**Comment by dolonfly** [comment]
http://gallery.echartsjs.com/chart/list?builtinTags%5B%5D=category-work&sortBy=rank&pageSize=32&pageNumber=0&author=all
这个URL 302到了 http://static.tieba.baidu.com/tb/error.html?tc=28932261030842711818082716

**Comment by webliuxiang** [comment]
又打不开了
tc:15014595850490390282082915
