### ISSUE TITLE
打不开gallery网站

### ISSUE THREAD

**Issue by webliuxiang** [ecomfe/echarts-gallery-feedback#36]
## 问题描述
浏览器打开gallery网页报错
![image](https://user-images.githubusercontent.com/25944130/44772273-feee9b00-ab9f-11e8-9afa-6ce5b7f35ae3.png)
![image](https://user-images.githubusercontent.com/25944130/44772312-162d8880-aba0-11e8-9989-06b8db184e03.png)
chrome和firefox均不能打开。
……

### 如果是 Gallery 打不开

请在下面提供 tracecode 以便我们排查问题。

Tracecode:15014595850490390282082915

Chrome：页面右键【检查】，在 Network 面板内，刷新后选择 html（如 `explore.html`），在右边的 Headers 中找到“Tracecode”填在上方。

没有提供该信息的 issue 将自动关闭。

**Comment by lijiews** [comment]
tc=34781046030842711818083015

**Comment by TiminZhao** [comment]
[![Uploading](url) 图片.png…]()

**Comment by houx15** [comment]
23062895300823640586090416

**Comment by yaowei9363** [comment]
Tracecode: 21804230460337166858090610

**Comment by songStar0904** [comment]
30773789550842711818090614

**Comment by cm16** [comment]
06850527770337166858090616

**Comment by xqs121** [comment]
00940136350473613066091215
