### ISSUE TITLE
Gallery 打不开

### ISSUE THREAD

**Issue by Life-Winner** [ecomfe/echarts-gallery-feedback#39]
## 问题描述

……

### 如果是 Gallery 打不开

请在下面提供 tracecode 以便我们排查问题。

Tracecode:00203646290473613066090611

Chrome：页面右键【检查】，在 Network 面板内，刷新后选择 html（如 `explore.html`），在右边的 Headers 中找到“Tracecode”填在上方。

没有提供该信息的 issue 将自动关闭。

**Comment by zhaoyixiao** [comment]
16579890990823640586090611

**Comment by zhaoyixiao** [comment]
什么情况，经常出现啊

**Comment by songStar0904** [comment]
30773789550842711818090614

**Comment by YuThree** [comment]
这个问题出现频率太高了

**Comment by xqs121** [comment]
06397454680842711818091215

**Comment by iilee** [comment]
01642358420842711818091315
