### ISSUE TITLE
gallery经常打不开 Tracecode:25595693780859423498091415

### ISSUE THREAD

**Issue by wcheryl** [ecomfe/echarts-gallery-feedback#41]
## 问题描述

……

### 如果是 Gallery 打不开

请在下面提供 tracecode 以便我们排查问题。

Tracecode:

Chrome：页面右键【检查】，在 Network 面板内，刷新后选择 html（如 `explore.html`），在右边的 Headers 中找到“Tracecode”填在上方。

没有提供该信息的 issue 将自动关闭。

**Comment by webestWang** [comment]
我这边也出现了，并且页面跳转到了贴吧404页面

**Comment by webestWang** [comment]
附带tracecode: 06848292820337166858091416

**Comment by Ovilia** [comment]
近期改善过 gallery 了，应该这个问题基本都解决了。
