### ISSUE TITLE
页面字体图片变成小尺寸的

### ISSUE THREAD

**Issue by pretty8816** [ecomfe/echarts-gallery-feedback#43]
## 问题描述

……

### 如果是 Gallery 打不开

请在下面提供 tracecode 以便我们排查问题。

Tracecode:

Chrome：页面右键【检查】，在 Network 面板内，刷新后选择 html（如 `explore.html`），在右边的 Headers 中找到“Tracecode”填在上方。

没有提供该信息的 issue 将自动关闭。

**Comment by Ovilia** [comment]
什么字体图片？
