### ISSUE TITLE
关于水球图字体样式能不正常设置

### ISSUE THREAD

**Issue by MH-Blog** [ecomfe/echarts-gallery-feedback#45]
## 问题描述
本地引入echarts核心包后再讲水球图依赖包引入，可正常渲染出水球图，但是在label.normal.textStyle下设置fontSize和insideColor都是无效的，只有通过需改水球图依赖包源js文件才能设置大小和样式。

**Comment by Ovilia** [comment]
请使用最新版的代码，如果还有问题，请在 https://github.com/ecomfe/echarts-liquidfill/issues 提问
