### ISSUE TITLE
地图使用geojson绘制出现问题

### ISSUE THREAD

**Issue by AN-535** [ecomfe/echarts-gallery-feedback#46]
## 问题描述

使用geojson绘制的地图，
![image](https://user-images.githubusercontent.com/33016525/55540025-a1ea3300-56f4-11e9-8f36-fb5b8d9564fb.png)
中间应该是空的，但是选择外部的时候，内部一同被选择了，相同的数据在http://geojson.io中展现的是正常的，
![image](https://user-images.githubusercontent.com/33016525/55540127-df4ec080-56f4-11e9-86b1-c20dd20ca48f.png)

**Comment by Ovilia** [comment]
请关注 https://github.com/ecomfe/zrender/pull/451
