### ISSUE TITLE
点开实例返回的问题

### ISSUE THREAD

**Issue by newnewStudy** [ecomfe/echarts-gallery-feedback#47]
## 问题描述
gallery里面，点开一个实例，再返回的时候，能不能返回我点开的位置，不要返回到首页。
……

### 如果是 Gallery 打不开

请在下面提供 tracecode 以便我们排查问题。

Tracecode:

Chrome：页面右键【检查】，在 Network 面板内，刷新后选择 html（如 `explore.html`），在右边的 Headers 中找到“Tracecode”填在上方。

没有提供该信息的 issue 将自动关闭。

**Comment by Ovilia** [comment]
这个不太好实现…
