### ISSUE TITLE
如何删除之前的版本？

### ISSUE THREAD

**Issue by wuruihua** [ecomfe/echarts-gallery-feedback#5]
如何删除之前的版本？只保留最新版

**Comment by Ovilia** [comment]
默认打开的是最新版本，删旧版本的目的是？

**Comment by wuruihua** [comment]
好比是垃圾 不用的自然需要清除 或者纯粹用户主体意愿就是想删除 这个是功能设计的完善性考虑 而且 如果不删除的话 文件会越来越多 对负载也会有一定的影响

**Comment by Ovilia** [comment]
目前不打算支持这样的功能，如果实在想删除，可以克隆一个，然后删除原图表
