### ISSUE TITLE
自己新建的图表,保存为只能自己看见,后期想更改为让所有人看见改不了..................

### ISSUE THREAD

**Issue by xushanpei** [ecomfe/echarts-gallery-feedback#50]
## 问题描述

……

### 如果是 Gallery 打不开

请在下面提供 tracecode 以便我们排查问题。

Tracecode:

Chrome：页面右键【检查】，在 Network 面板内，刷新后选择 html（如 `explore.html`），在右边的 Headers 中找到“Tracecode”填在上方。

没有提供该信息的 issue 将自动关闭。

**Comment by xushanpei** [comment]
自己新建的图表,保存为只能自己看见,后期想更改为让所有人看见改不了..................

**Comment by Ovilia** [comment]
右上角评论按钮，点开有个「修改」可以改，抱歉设计得比较隐晦，现在也没什么空改设计
