### ISSUE TITLE
官网的图表截图都没有了，这怎么看图表？还有点开的时候能不能新开一个窗口？

### ISSUE THREAD

**Issue by pilipilis** [ecomfe/echarts-gallery-feedback#51]
## 问题描述

……

### 如果是 Gallery 打不开

请在下面提供 tracecode 以便我们排查问题。

Tracecode:
![image](https://user-images.githubusercontent.com/48707657/59248515-3c1aaa00-8c55-11e9-8d7b-2d53bfdb387d.png)

Chrome：页面右键【检查】，在 Network 面板内，刷新后选择 html（如 `explore.html`），在右边的 Headers 中找到“Tracecode”填在上方。

没有提供该信息的 issue 将自动关闭。

**Comment by Ovilia** [comment]
谢谢反馈，正在修复中
