### ISSUE TITLE
echarts的社区示例的截图看不到，急急急！！！

### ISSUE THREAD

**Issue by JoyceLeez** [ecomfe/echarts-gallery-feedback#53]
## 问题描述

……

### 如果是 Gallery 打不开

请在下面提供 tracecode 以便我们排查问题。

Tracecode:

Chrome：页面右键【检查】，在 Network 面板内，刷新后选择 html（如 `explore.html`），在右边的 Headers 中找到“Tracecode”填在上方。

没有提供该信息的 issue 将自动关闭。

**Comment by q1w2e3r4wwww** [comment]
Tracecode:19964994450337166858061214

**Comment by q1w2e3r4wwww** [comment]
第二次刷新，Tracecode:21899004940859423498061214

**Comment by zuiaishuilanjiao** [comment]
所有示例图片请求都404了

**Comment by zuiaishuilanjiao** [comment]
Tracecode: 08441138090473613066061215

**Comment by lvruijing** [comment]
12333557890842711818061218

**Comment by Eric33011** [comment]
18033753760473613066061218

**Comment by Ovilia** [comment]
不好意思，因为服务器迁移，这部分功能正在紧急修复中，请耐心等待

**Comment by AKindOf** [comment]
Tracecode: 35398368090490390282061415

**Comment by Ovilia** [comment]
已经优先修复了一些排名比较靠前的缩略图，剩余部分正在陆续恢复中。
