### ISSUE TITLE
echart 图例看不了啊

### ISSUE THREAD

**Issue by Bigdaniel123** [ecomfe/echarts-gallery-feedback#54]
## 问题描述

……

### 如果是 Gallery 打不开

请在下面提供 tracecode 以便我们排查问题。

Tracecode:

Chrome：页面右键【检查】，在 Network 面板内，刷新后选择 html（如 `explore.html`），在右边的 Headers 中找到“Tracecode”填在上方。

没有提供该信息的 issue 将自动关闭。

**Comment by Ovilia** [comment]
不好意思，因为服务器迁移，这部分功能正在紧急修复中，请耐心等待

**Comment by wangzhixi** [comment]
@Ovilia 什么时候能好🙏

**Comment by Ovilia** [comment]
已经优先修复了一些排名比较靠前的缩略图，剩余部分正在陆续恢复中。
