### ISSUE TITLE
图片无法显示

### ISSUE THREAD

**Issue by industry-team** [ecomfe/echarts-gallery-feedback#56]
## 问题描述

……

###Gallery 图片无法打开

Tracecode:

https://gallery.echartsjs.com/explore.html#sort=rank~timeframe=all~author=all

没有提供该信息的 issue 将自动关闭。

**Comment by Ovilia** [comment]
已经优先修复了一些排名比较靠前的缩略图，剩余部分正在陆续恢复中。
