### ISSUE TITLE
自己上传的作品图片丢失了

### ISSUE THREAD

**Issue by fukeli** [ecomfe/echarts-gallery-feedback#59]
## 问题描述
自己的作品，是上传的本地图片，今天发现现实不出来了， 还不能重新上传图片

**Comment by Ovilia** [comment]
非常抱歉，最近在恢复之前丢失的截图。理论上原先有截图的话不会覆盖，请提供下作品地址，我看下是什么问题引起的。
可以修改截图的，我刚试了一下没问题。点页面右上角详情及评论（爱心左边的按钮），点「修改」，然后可以重新截图或上传。

**Comment by fukeli** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    非常感谢，已经看到图片恢复了。
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                www.fukeli
                            
                    
                        
                            
                                    www.fukeli@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2019年06月14日 23:22，Ovilia<notifications@github.com> 写道： 


非常抱歉，最近在恢复之前丢失的截图。理论上原先有截图的话不会覆盖，请提供下作品地址，我看下是什么问题引起的。
可以修改截图的，我刚试了一下没问题。点页面右上角详情及评论（爱心左边的按钮），点「修改」，然后可以重新截图或上传。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by wlcgit** [comment]
还有部分图片缺失

**Comment by Ovilia** [comment]
@wlcgit 请提供一下丢失作品的地址。@fukeli 在这段时间里其实我没有改动……

**Comment by SmileRose** [comment]
https://gallery.echartsjs.com/editor.html?c=xuqmbQ15J7 图片地址丢失，还有部分图表图片丢失

**Comment by Ovilia** [comment]
@SmileRose 不好意思，可能需要手动再次上传一下……
