### ISSUE TITLE
图片丢失

### ISSUE THREAD

**Issue by wuruihua** [ecomfe/echarts-gallery-feedback#6]
![_2017-05-11t08-45-16 813z](https://cloud.githubusercontent.com/assets/12755809/25940600/3f05c4c8-3669-11e7-810a-446ee53585c3.png)

**Comment by hl-stone** [comment]
@pissang 遇到同样问题 控制台有错误，有些示例 代码根本打不开
![qq 20170511192411](https://cloud.githubusercontent.com/assets/26757108/25946875/774ce544-367f-11e7-9166-5507d4747aba.png)

**Comment by Ovilia** [comment]
已恢复，谢谢反馈
