### ISSUE TITLE
我问问如何提交自己的个人作品? 没有到入口啊

### ISSUE THREAD

**Issue by EMMMMMMMMMMMMM** [ecomfe/echarts-gallery-feedback#60]
## 问题描述

……

### 如果是 Gallery 打不开

请在下面提供 tracecode 以便我们排查问题。

Tracecode:

Chrome：页面右键【检查】，在 Network 面板内，刷新后选择 html（如 `explore.html`），在右边的 Headers 中找到“Tracecode”填在上方。

没有提供该信息的 issue 将自动关闭。

**Comment by Ovilia** [comment]
https://gallery.echartsjs.com/editor.html 先登录，然后保存就可以。

**Comment by EMMMMMMMMMMMMM** [comment]
请问如何发布作品呢?  我已经登录保存了  到了个人中心却是空白的




------------------ 原始邮件 ------------------
发件人: "Ovilia"<notifications@github.com>;
发送时间: 2019年7月2日(星期二) 下午2:07
收件人: "ecomfe/echarts-gallery-feedback"<echarts-gallery-feedback@noreply.github.com>;
抄送: "嘻嘻嘻嘻嘻"<1097860389@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ecomfe/echarts-gallery-feedback] 我问问如何提交自己的个人作品? 没有到入口啊 (#60)




https://gallery.echartsjs.com/editor.html 先登录，然后保存就可以。

**Comment by Ovilia** [comment]
@EMMMMMMMMMMMMM 那应该就是发布了，你的地址发我一下？

**Comment by EMMMMMMMMMMMMM** [comment]
你好 是哪个地址呢? 还是账号



------------------ 原始邮件 ------------------
发件人: "Ovilia"<notifications@github.com>; 
发送时间: 2019年7月2日(星期二) 下午4:31
收件人: "ecomfe/echarts-gallery-feedback"<echarts-gallery-feedback@noreply.github.com>; 
抄送: "嘻嘻嘻嘻嘻"<1097860389@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [ecomfe/echarts-gallery-feedback] 我问问如何提交自己的个人作品? 没有到入口啊 (#60)




@EMMMMMMMMMMMMM 那应该就是发布了，你的地址发我一下？

**Comment by EMMMMMMMMMMMMM** [comment]
你好  我不是很清楚你说的地址是哪个 方便截图演示一下么?




------------------ 原始邮件 ------------------
发件人: "Ovilia"<notifications@github.com>;
发送时间: 2019年7月2日(星期二) 下午4:31
收件人: "ecomfe/echarts-gallery-feedback"<echarts-gallery-feedback@noreply.github.com>;
抄送: "嘻嘻嘻嘻嘻"<1097860389@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [ecomfe/echarts-gallery-feedback] 我问问如何提交自己的个人作品? 没有到入口啊 (#60)




@EMMMMMMMMMMMMM 那应该就是发布了，你的地址发我一下？

**Comment by Ovilia** [comment]
右上角头像，点自己的用户名，把地址复制给我

**Comment by EMMMMMMMMMMMMM** [comment]
https://gallery.echartsjs.com/explore.html?u=bd-1233223950&type=work#sort=rank~timeframe=all~author=all

**Comment by Ovilia** [comment]
确定是登录后保存的图表吗？不太清楚为什么……

**Comment by EMMMMMMMMMMMMM** [comment]
是登录后保存的  但是 在我的个人作品那里却没有出现

**Comment by Ovilia** [comment]
无法复现。
