### ISSUE TITLE
gallery列表页里的内容点击后不是新开一个窗口打开，每次还要返回才能看第二个

### ISSUE THREAD

**Issue by WaterDemon** [ecomfe/echarts-gallery-feedback#63]
## gallery列表页里的内容点击后不是新开一个窗口打开，每次还要返回才能看第二个

……
建议给跳转用的A标签加个target

**Comment by Ovilia** [comment]
不同人对打开标签的默认行为有不同的偏好，默认打开新窗口会给一些用户带来困扰。建议有需要的话自己右键新页面打开。
