### ISSUE TITLE
站点的demo都没了

### ISSUE THREAD

**Issue by zyh819heng** [ecomfe/echarts-gallery-feedback#69]
![image](https://user-images.githubusercontent.com/22977205/101609469-f73a2400-3a41-11eb-83ca-84c277b833d8.png)

**Comment by zyh819heng** [comment]
![image](https://user-images.githubusercontent.com/22977205/101610288-ffdf2a00-3a42-11eb-8d50-c7871cadbd94.png)

**Comment by zyh819heng** [comment]
![image](https://user-images.githubusercontent.com/22977205/101611836-f787ee80-3a44-11eb-87d8-db2f28e54aa5.png)

**Comment by Ovilia** [comment]
感谢反馈，昨晚已恢复
