### ISSUE TITLE
axisPointer设置后，悬停提示和图例显示颠倒

### ISSUE THREAD

**Issue by 122504387** [ecomfe/echarts-gallery-feedback#7]
> 全局axisPointer设置后，悬停提示和图例显示颠倒；查找API都没能解决该问题。
官方示例地址：http://echarts.baidu.com/demo.html#grid-multiple
希望能给出解决此问题的方法

**Comment by Ovilia** [comment]
这里的 issue 只针对 Gallery，相关问题请到 ECharts issue 提问。
