### ISSUE TITLE
Gallery 打不开

### ISSUE THREAD

**Issue by chrvip** [ecomfe/echarts-gallery-feedback#70]
## 问题描述

……

### 如果是 Gallery 打不开
![image](https://user-images.githubusercontent.com/536916/101609389-e25d9080-3a41-11eb-8bb5-5c83c62514a9.png)

请在下面提供 tracecode 以便我们排查问题。

Tracecode:08627526840490390282120917

Chrome：页面右键【检查】，在 Network 面板内，刷新后选择 html（如 `explore.html`），在右边的 Headers 中找到“Tracecode”填在上方。

没有提供该信息的 issue 将自动关闭。

**Comment by chrvip** [comment]
![image](https://user-images.githubusercontent.com/536916/101609764-55ff9d80-3a42-11eb-9164-9abb7db8c96a.png)

**Comment by zyh819heng** [comment]
Request URL: https://www.makeapie.com/user
Referrer Policy: strict-origin-when-cross-origin
Connection: keep-alive
Content-Length: 154
Content-Type: text/html
Date: Wed, 09 Dec 2020 10:01:56 GMT
Location: http://www.baidu.com/search/error.html?tc=01063739390859423498120918
P3p: CP=" OTI DSP COR IVA OUR IND COM "
Server: Apache
Set-Cookie: BAIDUID=9B3B527D8B6B592412BC71226AF5597F:FG=1; expires=Thu, 09-Dec-21 10:01:56 GMT; max-age=31536000; path=/; domain=.baidu.com; version=1
Strict-Transport-Security: max-age=31536000
Tracecode: 01063739390859423498120918
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9
Cache-Control: no-cache
Connection: keep-alive
Cookie: Hm_lvt_99f7569c6c41b300eebba455946c8b45=1607506100; Hm_lpvt_99f7569c6c41b300eebba455946c8b45=1607507925
Host: www.makeapie.com
Pragma: no-cache
Referer: https://www.makeapie.com/explore.html
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
X-Requested-With: XMLHttpRequest

**Comment by zyh819heng** [comment]
Request URL: https://www.makeapie.com/chart/list?builtinTags%5B%5D=category-work&sortBy=rank&pageSize=32&pageNumber=0&author=all
Referrer Policy: strict-origin-when-cross-origin
Connection: keep-alive
Content-Length: 154
Content-Type: text/html
Date: Wed, 09 Dec 2020 10:02:06 GMT
Location: http://www.baidu.com/search/error.html?tc=01164784100490390282120918
P3p: CP=" OTI DSP COR IVA OUR IND COM "
Server: Apache
Set-Cookie: BAIDUID=C0A5FE4D61BEC8DDEB43CFAF6478760F:FG=1; expires=Thu, 09-Dec-21 10:02:06 GMT; max-age=31536000; path=/; domain=.baidu.com; version=1
Strict-Transport-Security: max-age=31536000
Tracecode: 01164784100490390282120918
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9
Cache-Control: no-cache
Connection: keep-alive
Cookie: Hm_lvt_99f7569c6c41b300eebba455946c8b45=1607506100; Hm_lpvt_99f7569c6c41b300eebba455946c8b45=1607508107
Host: www.makeapie.com
Pragma: no-cache
Referer: https://www.makeapie.com/explore.html
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
X-Requested-With: XMLHttpRequest
builtinTags[]: category-work
sortBy: rank
pageSize: 32
pageNumber: 0
author: all

**Comment by MoonWaveJs** [comment]
Tracecode: 21873547100823640586120920

**Comment by Ovilia** [comment]
感谢反馈，昨晚已恢复

**Comment by foxbaby213** [comment]
09719765920823640586121119

**Comment by zyh819heng** [comment]
也不知道什么时候修复好 找知道不然ui超上面的东西了 本想这样快一点 现在都要自己写 简直要疯了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "foxbaby213"<notifications@github.com&gt;; 
发送时间: 2020年12月11日(星期五) 晚上7:18
收件人: "ecomfe/echarts-gallery-feedback"<echarts-gallery-feedback@noreply.github.com&gt;; 
抄送: "！メ哼da哥！"<786583346@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [ecomfe/echarts-gallery-feedback] Gallery 打不开 (#70)





 
09719765920823640586121119
