### ISSUE TITLE
Gallery 又打不开了

### ISSUE THREAD

**Issue by zyh819heng** [ecomfe/echarts-gallery-feedback#71]
![image](https://user-images.githubusercontent.com/22977205/101873795-925a0780-3bc2-11eb-8a47-77b809cf3561.png)
![image](https://user-images.githubusercontent.com/22977205/101873847-ad2c7c00-3bc2-11eb-858a-6bb05518ac20.png)

**Comment by zyh819heng** [comment]
Mixed Content: The page at 'https://www.makeapie.com/explore.html#charts=lines~sort=rank~timeframe=all~author=all' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.baidu.com/search/error.html?tc=04249187380490390282121115'. This request has been blocked; the content must be served over HTTPS.

**Comment by zyh819heng** [comment]
Tracecode: 06188460890823640586121115

**Comment by Litttle-butterfly** [comment]
我能问问 林峰不在以后，为啥变得如此垃圾了吗？
什么鬼我从1.4一直关注到他现在，变得越来越不成样子了！！！！！！！！！！！！！！！！！！！1

**Comment by zyh819heng** [comment]
真实太坑了 都让设计直接抄这里的样式的 这边打不开被坑出血了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "小翼"<notifications@github.com&gt;; 
发送时间: 2020年12月11日(星期五) 下午3:40
收件人: "ecomfe/echarts-gallery-feedback"<echarts-gallery-feedback@noreply.github.com&gt;; 
抄送: "！メ哼da哥！"<786583346@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ecomfe/echarts-gallery-feedback] Gallery 又打不开了 (#71)





 
我能问问 林峰不在以后，为啥变得如此垃圾了吗？
 什么鬼我从1.4一直关注到他现在，变得越来越不成样子了！！！！！！！！！！！！！！！！！！！1

**Comment by Litttle-butterfly** [comment]
肯定是有人上传了dirty数据，所以才会出现这种情况!
无语，不弄个审核机制 啥都能上传

**Comment by maybeyourking** [comment]
希望尽快修复！

**Comment by reactjser** [comment]
Gallery地址是哪个？@zyh819heng

**Comment by foxbaby213** [comment]
09719765920823640586121119

**Comment by geniusadventurer** [comment]
又打不开啦！手上有活急着用，很烦……

**Comment by YaoYuebing** [comment]
求大佬修复

**Comment by ys395853952** [comment]
难受啊

**Comment by bingzaimmd** [comment]
为啥没人会看这里,感觉反馈了也没啥用

**Comment by pissang** [comment]
抱歉正在修复中

**Comment by daimashenjing** [comment]
![image](https://user-images.githubusercontent.com/8486201/101989726-75662700-3cdd-11eb-8bd3-7b0043cd1b19.png)

**Comment by Ovilia** [comment]
已修复，非常抱歉给大家带来不便

**Comment by zyh819heng** [comment]
终于好了 感谢
