### ISSUE TITLE
保存按钮失灵

### ISSUE THREAD

**Issue by wuruihua** [ecomfe/echarts-gallery-feedback#8]
http://gallery.echartsjs.com/editor.html

**Comment by Ovilia** [comment]
没问题啊，刷新试试？

**Comment by wuruihua** [comment]
刷新了 确实不起作用 无响应
![default](https://user-images.githubusercontent.com/12755809/31699610-63dbbcb6-b3f6-11e7-81e3-140397d57ff6.PNG)

**Comment by Ovilia** [comment]
有报错吗？什么信息都没有？控制台？

**Comment by wuruihua** [comment]
在 'DOMWindow' 上执行 'postMessage' 失败：提供的目标源 ('http://gallerybox.echartsjs.com') 与接收者窗口的源 ('http://envi.ckcest.cn') 不匹配。

**Comment by Ovilia** [comment]
代码提供一下？

**Comment by reloadbug** [comment]
好像跟图表中图片过多有关,今天创建的代码里面有很多书的图片,数量不多的时候可以保持,数量过多(40个),无非生成预览,点击保存按钮也没反应,只要注释掉图片代码刷新就又能保存了.

**Comment by reloadbug** [comment]
无法保存的项目:http://gallery.echartsjs.com/editor.html?c=xSy0DESDzz

**Comment by Ovilia** [comment]
是项目没法保存，还是截图有问题？
